# Welcome to Jekyll!
#

# Site settings
title: Space Apps Zaragoza
description: |
  23 y 24 de Abril
owner: Borja Espejo 
first_published: 2016
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>

# Build settings
markdown: kramdown
#sass:
#  style: compressed
